routes/web.php
<?php

use App\Http\Controllers\Api\LocationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NodeController;
use App\Http\Controllers\System\MyPortalController;
use App\Http\Controllers\System\ProjectController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth'], 'namespace' => 'System'], function (){
    //My Portal
    Route::get('my-portal', [MyPortalController::class, 'index']);
    //projects
    Route::group(['prefix' => 'projects'], function (){
        Route::get('create', [Projectcontroller::class, 'create']);
    });
});

Route::group(['middleware' => ['auth']], function (){
    //Template
    Route::get('templates/{template}', [TemplateController::class, 'index']);
    Route::get('templates/{template}/create', [TemplateController::class, 'create']);
    Route::post('templates/{template}/create', [TemplateController::class, 'store']);

    Route::get('nodes/{node}', [NodeController::class, 'edit']);
    Route::post('nodes/{node}', [NodeController::class, 'update']);
});

//api
Route::group(['prefix' => 'api'], function (){
    //provinces
    Route::get('department/provinces/{department:name}', [LocationController::class, 'provinces']);
    Route::get('province/districts/{province:name}', [LocationController::class, 'districts']);
});

app/Models/Field.php
<?php

namespace App\Models;

use App\Models\Location\Department;
use Illuminate\Database\Eloquent\Model;

class Field extends Model
{
    const LABEL = 1;
    const TEXT = 2;
    const SELECT = 3;
    const CHECKBOX = 4;
    const TEXTAREA = 5;
    const FILE = 6;
    const IMAGE = 7;
    const RADIO = 8;
    const NAV_TAP = 9;
    const TAB = 10;
    const MAP = 11;

    public function options()
    {
        return $this->hasMany(Field::class, 'parent_id');
    }

    public function node_fields()
    {
        return $this->hasMany(NodeField::class);
    }

    public function node_field_value($nodeId)
    {
        if (!$nodeId)
            return '';

        $query = $this->node_fields()
            ->where('field_id', $this->id)
            ->where('node_id', $nodeId);

        if ($query->count() > 1 || $this->type_domain == Field::CHECKBOX || $this->type_domain == Field::IMAGE) {
            return $query->pluck('value')->toArray();

        } else {
            $nodeField = $query->first(['value']);

            if (!$nodeField)
                return '';

            return $nodeField->value;
        }
    }

    public function getDataOptionsAttribute()
    {
        if ($this->getLayoutNameAttribute() == 'department')
            return Department::all();

        return $this->options;
    }

    public function getColAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return 12;

        $layout = $obj->{'layout'};

        if (!$layout || !$layout->{'col'})
            return 12;

        return $layout->{'col'};
    }

    public function getTypeAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return 'text';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'type'}))
            return 'text';

        return $layout->{'type'};
    }

    public function getClearfixAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return '';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'clearfix'}))
            return '';

        return $layout->{'clearfix'} ? '<div class="clearfix"></div>' : '';
    }

    public function getLayoutNameAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return '';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'name'}))
            return '';

        return $layout->{'name'};
    }

    public function getLayoutWidthAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return '';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'width'}))
            return '';

        return $layout->{'width'};
    }

    public function getLayoutHeightAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return '';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'height'}))
            return '';

        return $layout->{'height'};
    }

    public function getLayoutSizeAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return '';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'size'}))
            return '';

        return $layout->{'size'};
    }

    public function getLayoutSuffixAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return '';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'suffix'}))
            return '';

        return $layout->{'suffix'};
    }

    public function getLayoutApiUrlAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return false;

        $layout = $obj->{'layout'};

        if(!isset($layout->{'api_url'}))
            return false;

        return $layout->{'api_url'};
    }

    public function getLayoutDisabledElementsAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return [];

        $layout = $obj->{'layout'};

        if(!isset($layout->{'disabled_elements'}))
            return [];

        return $layout->{'disabled_elements'};
    }

    public function getLayoutEffectedElementAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return false;

        $layout = $obj->{'layout'};

        if(!isset($layout->{'effected_element'}))
            return false;

        return $layout->{'effected_element'};
    }

    public function getLayoutClassAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return false;

        $layout = $obj->{'layout'};

        if(!isset($layout->{'class'}))
            return false;

        return $layout->{'class'};
    }

    public function getLayoutPlaceholderAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'layout'}))
            return '';

        $layout = $obj->{'layout'};

        if(!isset($layout->{'placeholder'}))
            return '';

        return $layout->{'placeholder'};
    }

    public function getValidationsAttribute()
    {
        $obj = json_decode($this->json_param);

        if (!isset($obj->{'validations'}))
            return '';

        return $obj->{'validations'};
    }
}

resources/views/includes/fields/checkbox.blade.php
<div class="col-md-{{ $field->col }}">
    <div class="form-group @error($field->layout_name) has-error @enderror">
        <label for="description">{{ $field->name }}</label>
        <div class="row">
            @foreach($field->options as $option)
                <div class="col-md-{{ $option->col }}">
                    <div class="checkbox checkbox-primary">
                        <input type="checkbox" name="{{ $field->layout_name }}[]"
                               {{ $option->type_domain == \App\Models\Field::CHECKBOX || $option->options->count() > 0 ? 'data-checkbox' : 'data-checked' }}
                               id="{{ $option->id }}" value="{{ $option->name }}"
                            {{ old($field->layout_name, $field->node_field_value($nodeId)) ? (in_array($option->name, old($field->layout_name, $field->node_field_value($nodeId))) ? 'checked' : '') : '' }}>
                        <label for="{{ $option->id }}">
                            @if($option->type_domain == \App\Models\Field::TEXT)
                                <div class="form-inline @error($option->layout_name) has-error @enderror">
                                    <span>{{ $option->name }}</span>
                                    <input type="{{ $option->type }}" class="form-control input-text" id="{{ $option->layout_name }}"
                                           {{ old($field->layout_name, $field->node_field_value($nodeId)) ? (in_array($option->name, old($field->layout_name, $field->node_field_value($nodeId))) ?: 'disabled') : 'disabled' }}
                                           name="{{ $option->layout_name }}" value="{{ old($option->layout_name, $option->node_field_value($nodeId)) }}">
                                    <span>{{ $option->layout_suffix }}</span>
                                    @error($option->layout_name)
                                    <span class="help-block"><strong>{{ $message }}</strong></span>
                                    @enderror
                                </div>
                            @else
                                {{ $option->name }}
                            @endif
                        </label>
                        @if($option->type_domain == \App\Models\Field::CHECKBOX || $option->type_domain == \App\Models\Field::TEXT)
                            @foreach($option->options as $subOption)
                                <div class="checkbox checkbox-primary">
                                    <input type="checkbox" name="{{ $field->layout_name }}[]" class="form-check" data-checked
                                           id="{{ $subOption->id }}" value="{{ $subOption->name }}"
                                        {{ old($field->layout_name, $field->node_field_value($nodeId)) ? (in_array($option->name, old($field->layout_name, $field->node_field_value($nodeId))) ?: 'disabled') : 'disabled' }}
                                        @if($subOption->type_domain == \App\Models\Field::TEXT)
                                            {{ old($subOption->layout_name, $subOption->node_field_value($nodeId)) ? 'checked' : '' }}
                                        @else
                                        {{ old($field->layout_name, $field->node_field_value($nodeId)) ? (in_array($subOption->name, old($field->layout_name, $field->node_field_value($nodeId))) ? 'checked' : '') : '' }}
                                        @endif
                                    >
                                    <label for="{{ $subOption->id }}">
                                        @if($subOption->type_domain == \App\Models\Field::TEXT)
                                            <div class="form-inline @error($subOption->layout_name) has-error @enderror">
                                                <span>{{ $subOption->name }}</span>
                                                <input type="{{ $subOption->type }}" class="form-control" id="{{ $subOption->layout_name }}"
                                                       name="{{ $subOption->layout_name }}" value="{{ old($subOption->layout_name, $subOption->node_field_value($nodeId)) }}"
                                                    {{ old($subOption->layout_name, $subOption->node_field_value($nodeId)) ?: 'disabled' }}>
                                                <span>{{ $subOption->layout_suffix }}</span>
                                                @error($subOption->layout_name)
                                                <span class="help-block"><strong>{{ $message }}</strong></span>
                                                @enderror
                                            </div>
                                        @elseif($subOption->type_domain == \App\Models\Field::SELECT)
                                            <div class="form-inline @error($subOption->layout_name) has-error @enderror">
                                                <span>{{ $subOption->name }}</span>
                                                <select name="{{ $subOption->layout_name }}" id="{{ $subOption->layout_name }}" class="form-control"
                                                    {{ old($subOption->layout_name, $subOption->node_field_value($nodeId)) ?: 'disabled' }}>
                                                    <option value="">Seleccione</option>
                                                    @foreach($subOption->options as $label)
                                                        <option value="{{ $label->name }}"
                                                                {{ old($subOption->layout_name, $subOption->node_field_value($nodeId)) == $label->name ? 'selected' : '' }}
                                                        >{{ $label->name }}</option>
                                                    @endforeach
                                                </select>
                                                @error($subOption->layout_name)
                                                <span class="help-block"><strong>{{ $message }}</strong></span>
                                                @enderror
                                            </div>
                                        @else
                                            {{ $subOption->name }}
                                        @endif
                                    </label>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            @endforeach
        </div>
        @error($field->layout_name)
        <span class="help-block"><strong>{{ $message }}</strong></span>
        @enderror
    </div>
</div>
{!! $field->clearfix !!}

resources/views/includes/fields/general.blade.php
@switch($field->type_domain)
    @case(\App\Models\Field::TEXT)
    @include('includes.fields.text')
    @break

    @case(\App\Models\Field::SELECT)
    @include('includes.fields.select')
    @break

    @case(\App\Models\Field::CHECKBOX)
    @include('includes.fields.checkbox')
    @break

    @case(\App\Models\Field::TEXTAREA)
    @include('includes.fields.textarea')
    @break

    @case(\App\Models\Field::IMAGE)
    @include('includes.fields.image')
    @break

    @case(\App\Models\Field::RADIO)
    @include('includes.fields.radio')
    @break

    @case(\App\Models\Field::MAP)
    @include('includes.fields.map')
    @break
@endswitch

resources/views/includes/fields/image.blade.php
<div class="col-md-{{ $field->col }} m-b-10 contentImage">
    <h5 class="font-bold">
        {{ $field->name }}
        <button type="button" data-add class="btn btn-sm btn-success waves-effect waves-light">
            <i class="fa fa-plus"></i>
        </button>
    </h5>
    <div id="contentInputs">
        <div class="form-inline m-b-15 @error($field->layout_name) has-error @enderror">
            <div class="form-group m-r-10">
                <label for="width">Ancho</label>
                <input type="text" class="form-control" id="width"
                       data-max-size="{{ $field->layout_size }}" value="{{ $field->layout_width }}">
            </div>
            <div class="form-group m-r-10">
                <label for="height">Alto</label>
                <input type="text" class="form-control" id="height" value="{{ $field->layout_height }}">
            </div>
            <input type="file" id="images" name="{{ $field->layout_name }}[]" accept="image/*"
                   multiple="multiple" data-image>
            <br>
            <span class="text-danger" id="alert"></span>
            @error($field->layout_name)
            <span class="help-block"><strong>{{ $message }}</strong></span>
            @enderror
        </div>
    </div>
    <template id="template">
        <div class="form-inline m-b-15 @error($field->layout_name) has-error @enderror">
            <div class="form-group m-r-10">
                <label for="width">Ancho</label>
                <input type="text" class="form-control" id="width"
                       data-max-size="{{ $field->layout_size }}" value="{{ $field->layout_width }}">
            </div>
            <div class="form-group m-r-10">
                <label for="height">Alto</label>
                <input type="text" class="form-control" id="height" value="{{ $field->layout_height }}">
            </div>
            <input type="file" id="images" name="{{ $field->layout_name }}[]" accept="image/*"
                   multiple="multiple" {{ $field->layout_name == 'images' ? 'required' : '' }} data-image>
            <br>
            <span class="text-danger" id="alert"></span>
            @error($field->layout_name)
            <span class="help-block"><strong>{{ $message }}</strong></span>
            @enderror
        </div>
    </template>
    <div class="row m-t-20" id="contentImages">
        @if($field->node_field_value($nodeId))
            @foreach($field->node_field_value($nodeId) as $image)
                @if($image)
                    <div class="col-sm-2 position-relative">
                        <input type="hidden" name="value_{{$field->layout_name}}[]" value="{{ $image }}">
                        <img src="{{ asset('images/'.$field->layout_name.'/'.$image) }}" class="img-responsive" alt="">
                        <button data-delete type="button" class="btn btn-sm btn-danger" title="Eliminar" style="position: absolute; top: 0">
                            <i class="fa fa-trash"></i>
                        </button>
                    </div>
                @endif
            @endforeach
        @endif
    </div>
</div>

resources/views/includes/fields/map.blade.php
<div class="col-md-{{ $field->col }}">
    <div id="{{ $field->layout_name }}" style="height: 500px"></div>
    <input type="hidden" name="{{ $field->layout_name }}" value="{{ old($field->layout_name, $field->node_field_value($nodeId)) }}">
    @error($field->layout_name)
    <span class="text-danger"><strong>{{ $message }}</strong></span>
    @enderror
</div>

<script>
    let mymap = L.map({{ $field->layout_name }}).setView([-12.0463731,-77.042754], 6);

    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        maxZoom: 18,
        id: 'mapbox/streets-v11',
        tileSize: 512,
        zoomOffset: -1
    }).addTo(mymap);

    const oldValue = {{ old($field->layout_name, $field->node_field_value($nodeId)) ?: '[-12.12, -436.99]' }};

    let marker = L.marker(oldValue).addTo(mymap);

    function onMapClick(e) {
        marker.setLatLng(e.latlng);
        $('input[name="{{ $field->layout_name }}"]').val('['+e.latlng.lat+','+e.latlng.lng+']');
    }
    mymap.on('click', onMapClick);

    function getLatLng(lat, lng) {
        marker.setLatLng([lat,lng]);
        $('input[name="{{ $field->layout_name }}"]').val('['+lat+','+lng+']');
    }
</script>

resources/views/includes/fields/navbar.blade.php
<ul class="nav nav-tabs nav-justified">
    @foreach($field->options as $option)
    <li role="presentation" class="{{ $option->layout_class }}">
        <a href="#{{ $option->layout_name }}" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">{{ $option->name }}</a>
    </li>
    @endforeach
</ul>
<div class="tab-content">
    @foreach($field->options as $option)
        <div role="tabpanel" class="tab-pane fade {{ $option->layout_class ? 'in active' : '' }}" id="{{ $option->layout_name }}" aria-labelledby="{{ $option->layout_name }}-tab">
            <div class="row">
                @foreach($option->options as $subOption)
                    @include('includes.fields.general', ['field' => $subOption])
                @endforeach
            </div>
        </div>
    @endforeach
</div>

resources/views/includes/fields/radio.blade.php
<div class="col-md-{{ $field->col }}">
    <div class="form-group @error($field->layout_name) has-error @enderror">
        <label for="description">{{ $field->name }}</label>
{{--        <input type="hidden" name="field_ids[]" value="{{ $field->id }}">--}}
        <div class="row">
            @foreach($field->options as $option)
                <div class="col-md-{{ $option->col }}">
                    <div class="radio radio-primary">
                        <input type="radio" name="{{ $field->layout_name }}" data-checked id="{{ $option->id }}" value="{{ $option->name }}"
                            {{ old($field->layout_name, $field->node_field_value($nodeId)) == $option->name ? 'checked' : '' }}>
                        <label for="{{ $option->id }}">
                            @if($option->type_domain == \App\Models\Field::TEXT)
                                <div class="form-inline @error($option->layout_name) has-error @enderror">
                                    <span>{{ $option->name }}</span>
                                    <input type="{{ $option->type }}" class="form-control" id="{{ $option->layout_name }}"
                                           name="{{ $option->layout_name }}" value="{{ old($option->layout_name, $option->node_field_value($nodeId)) }}">
                                    <span>{{ $option->layout_suffix }}</span>
                                    @error($option->layout_name)
                                    <span class="help-block"><strong>{{ $message }}</strong></span>
                                    @enderror
                                </div>
                            @else
                                {{ $option->name }}
                            @endif
                        </label>
                    </div>
                </div>
            @endforeach
        </div>
        @error($field->layout_name)
        <span class="help-block"><strong>{{ $message }}</strong></span>
        @enderror
    </div>
</div>
{!! $field->clearfix !!}

resources/views/includes/fields/select.blade.php
<div class="col-md-{{ $field->col }}">
    <div class="form-group @error($field->layout_name) has-error @enderror">
        <label for="{{ $field->layout_name }}">{{ $field->name }}</label>
{{--        <input type="hidden" name="field_ids[]" value="{{ $field->id }}">--}}
        <select name="{{ $field->layout_name }}" id="{{ $field->layout_name }}" onchange="{{$field->layout_name}}Select($(this))" class="form-control">
            <option value="">Seleccione</option>
            @if($provinces && $field->layout_name == 'province')
                @foreach($provinces as $province)
                    <option value="{{ $province->name }}" {{ old($field->layout_name, $field->node_field_value($nodeId)) == $province->name ? 'selected' : '' }}>{{ $province->name }}</option>
                @endforeach
            @elseif($districts && $field->layout_name == 'district')
                @foreach($districts as $district)
                    <option value="{{ $district->name }}" {{ old($field->layout_name, $field->node_field_value($nodeId)) == $district->name ? 'selected' : '' }}>{{ $district->name }}</option>
                @endforeach
            @else
                @foreach($field->data_options as $option)
                    <option value="{{ $option->name }}" {{ old($field->layout_name, $field->node_field_value($nodeId)) == $option->name ? 'selected' : '' }}>{{ $option->name }}</option>
                @endforeach
            @endif
        </select>
        @error($field->layout_name)
        <span class="help-block"><strong>{{ $message }}</strong></span>
        @enderror
    </div>
</div>
{!! $field->clearfix !!}

@if($field->layout_api_url)
    <script>
        const $elements{{$field->layout_name}} = @json($field->layout_disabled_elements);
        const effectedElement{{$field->layout_name}} = @json($field->layout_effected_element);
        const url_prefix{{$field->layout_name}} = @json($field->layout_api_url);

        function {{$field->layout_name}}Select($this) {
            let selectId = $this.val();
            if (! selectId) {
                jQuery.each( $elements{{$field->layout_name}}, function( i, element ) {
                    const $element = $('#'+element);
                    $element.attr('disabled', true);
                    $element.html('<option value="">Seleccione</option>');
                });
                return;
            }
            jQuery.each( $elements{{$field->layout_name}}, function( i, element ) {
                const $element = $('#'+element);
                $element.attr('disabled', true);
                $element.html('<option value="">Seleccione</option>');
            });
            // AJAX
            $.get(url_prefix{{$field->layout_name}}+selectId, function (data_selects) {
                let html_select = '<option value="">Seleccione</option>';

                Array.from(data_selects).forEach(data_select => {
                    html_select += '<option value="'+data_select.name+'">'+data_select.name+'</option>';
                });
                const subSelect = $('#'+effectedElement{{$field->layout_name}});
                subSelect.html(html_select);
                subSelect.attr('disabled', false);
            });

            const $department = $('#department');
            const $province = $('#province');
            const $district = $('#district');

            let address = $district.val()+' '+$province.val()+' '+$department.val();

            $.getJSON('https://maps.googleapis.com/maps/api/geocode/json?address='+address+'%20PERU&key=AIzaSyBvuspZieDAMlpAVAe2qwlvkk8oQU34dtg', function(data) {
                const location = data.results[0].geometry.location;

                getLatLng(location.lat, location.lng);
            });
        }
    </script>
@endif
@if($field->layout_name == 'district')
    <script>
        const $elements{{$field->layout_name}} = @json($field->layout_disabled_elements);
        const effectedElement{{$field->layout_name}} = @json($field->layout_effected_element);
        const url_prefix{{$field->layout_name}} = @json($field->layout_api_url);

        function {{$field->layout_name}}Select($this) {
            const $department = $('#department');
            const $province = $('#province');
            const $district = $('#district');

            let address = $district.val()+' '+$province.val()+' '+$department.val();

            $.getJSON('https://maps.googleapis.com/maps/api/geocode/json?address='+address+'%20PERU&key=AIzaSyBvuspZieDAMlpAVAe2qwlvkk8oQU34dtg', function(data) {
                const location = data.results[0].geometry.location;

                getLatLng(location.lat, location.lng);
            });
        }
    </script>
@endif

resources/views/includes/fields/text.blade.php
<div class="col-md-{{ $field->col }}">
    <div class="form-group @error($field->layout_name) has-error @enderror">
        <label for="{{ $field->layout_name }}">{{ $field->name }}</label>
{{--        <input type="hidden" name="field_ids[]" value="{{ $field->id }}">--}}
        <input type="{{ $field->type }}" class="form-control" id="{{ $field->layout_name }}"
               name="{{ $field->layout_name }}" value="{{ old($field->layout_name, $field->node_field_value($nodeId)) }}" placeholder="{{ $field->layout_placeholder }}">
        @error($field->layout_name)
        <span class="help-block"><strong>{{ $message }}</strong></span>
        @enderror
    </div>
</div>
{!! $field->clearfix !!}

resources/views/includes/fields/textarea.blade.php
<div class="col-md-{{ $field->col }}">
    <div class="form-group @error($field->layout_name) has-error @enderror">
        <label for="{{ $field->layout_name }}">{{ $field->name }}</label>
{{--        <input type="hidden" name="field_ids[]" value="{{ $field->id }}">--}}
        <textarea id="{{ $field->layout_name }}" name="{{ $field->layout_name }}">{{ old($field->layout_name, $field->node_field_value($nodeId)) }}</textarea>
        @error($field->layout_name)
        <span class="help-block"><strong>{{ $message }}</strong></span>
        @enderror
    </div>
</div>
{!! $field->clearfix !!}