routes/web.php
<?php

use App\Http\Controllers\Api\LocationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NodeController;
use App\Http\Controllers\System\MyPortalController;
use App\Http\Controllers\System\ProjectController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth'], 'namespace' => 'System'], function (){
    //My Portal
    Route::get('my-portal', [MyPortalController::class, 'index']);
    //projects
    Route::group(['prefix' => 'projects'], function (){
        Route::get('create', [Projectcontroller::class, 'create']);
    });
});

Route::group(['middleware' => ['auth']], function (){
    //Template
    Route::get('templates/{template}', [TemplateController::class, 'index']);
    Route::get('templates/{template}/create', [TemplateController::class, 'create']);
    Route::post('templates/{template}/create', [TemplateController::class, 'store']);

    Route::get('nodes/{node}', [NodeController::class, 'edit']);
    Route::post('nodes/{node}', [NodeController::class, 'update']);
});

//api
Route::group(['prefix' => 'api'], function (){
    //provinces
    Route::get('department/provinces/{department:name}', [LocationController::class, 'provinces']);
    Route::get('province/districts/{province:name}', [LocationController::class, 'districts']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    CONST ROLE_GENERAL_ADMIN = 0;
    CONST ROLE_PROPERTY_ADMIN = 1;

    public function is($role)
    {
        return $this->role == $role;
    }

    public function getPhotoUrlAttribute()
    {
        return '/images/users/'.$this->photo;
    }

    public function getRoleNameAttribute()
    {
        if($this->role == 0)
            return 'Administrador general';
        else
            return 'Administrador de inmuebles';
    }
}

resources/views/includes/alert.blade.php
@if (session('notification'))
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ session('notification') }}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ session('error') }}
    </div>
@endif

resources/views/includes/menu.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!-- User -->
        <div class="user-box">
            <div class="user-img">
                <img src="{{ auth()->user()->photo_url }}" alt="user-img" title="{{ auth()->user()->name }}" class="img-circle img-thumbnail img-responsive">
                <div class="user-status online"><i class="zmdi zmdi-dot-circle"></i></div>
            </div>
            <h5><a href="#">{{ auth()->user()->name }}</a> </h5>
            <h6>{{ auth()->user()->role_name }}</h6>
            <ul class="list-inline">
                <li>
                    <a href="#" >
                        <i class="zmdi zmdi-settings"></i>
                    </a>
                </li>

                <li>
                    <a href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();" title="Cerrar sesión">
                        <i class="zmdi zmdi-power"></i>
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>
        </div>
        <!-- End User -->
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">Menú</li>
                @if (auth()->user()->is(0) || auth()->user()->is(1))
                    <li class="has_sub">
                        <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-cog"></i> <span> Sistema </span> <span class="menu-arrow"></span></a>
                        <ul class="list-unstyled">
                            <li><a href="{{ url('my-portal') }}"><span> Mi portal </span></a></li>
                            <li><a href="#"><span> Mensajes </span></a></li>
                            <li><a href="#"><span> Usuarios </span></a></li>
                        </ul>
                    </li>
                    <li class="has_sub">
                        <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-building"></i> <span> Inmuebles </span> <span class="menu-arrow"></span></a>
                        <ul class="list-unstyled">
                            <li><a href="{{ url('templates/1/create') }}"><span> Agregar </span></a></li>
                            <li><a href="{{ url('templates/1') }}"><span> Lista </span></a></li>
                        </ul>
                    </li>
                    <li class="has_sub">
                        <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-cogs"></i> <span> Proyectos </span> <span class="menu-arrow"></span></a>
                        <ul class="list-unstyled">
                            <li><a href="{{ url('templates/2/create') }}"><span> Agregar </span></a></li>
                            <li><a href="{{ url('templates/2') }}"><span> Lista </span></a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="waves-effect">
                            <i class="fa fa-file-text-o"></i> <span> Páginas</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="waves-effect">
                            <i class="fa fa-folder-open"></i> <span> Repositorio</span>
                        </a>
                    </li>
                @endif
            </ul>
            <div class="clearfix"></div>
        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>

    </div>

</div>
<!-- Left Sidebar End -->